glob: "app/views/**/*.{html,text,js}{+*,}.erb"
EnableDefaultLinters: false
linters:
  FinalNewline:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      AllCops:
        DisabledByDefault: true
      Style/StringLiterals:
        Enabled: true
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  SpaceIndentation:
    enabled: true
