default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    statement_timeout: 10000
    idle_in_transaction_session_timeout: 10000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_DATABASE'] %>

development:
  <<: *default
  database: 'bat_apply_development'

test:
  <<: *default
  database: bat_apply_test<%= ENV['TEST_ENV_NUMBER'] %>
  variables:
    idle_in_transaction_session_timeout: 0

production:
  <<: *default
  sslmode: require
